# Generated by Django 5.1.4 on 2026-02-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationverifycode',
            name='email',
        ),
    ]
