# Generated by Django 5.1.4 on 2026-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
